### ISSUE TITLE
Method file_version does not return version

### ISSUE THREAD

**Issue by pajlpajl** [shawnlaffan/Geo-ShapeFile#22]
The method file_version in ShapeFile.pm calls _get_shp_shx_header_value('file_version'), but this value is never set. The correct call is _get_shp_shx_header_value('version') since it is shp_version and shx_version set from the file header and not shp_file_version and shx_file_version.

**Comment by shawnlaffan** [comment]
Thanks for reporting this.  

Are you able to provide a pull request with a test?

**Comment by pajlpajl** [comment]
Not really sure how to go about that. We saw the issue dealing with empty shape files – the shx file is 100 bytes, as you know. So we could not get the file version and the extents were returning undefined values. Easy to load an empty shape file and try to get the lower_left_corner and file_version and see they fail.

0000000: 0000 270a 0000 0000 0000 0000 0000 0000  ..'.............
0000010: 0000 0000 0000 0000 0000 0032 e803 0000  ...........2....
0000020: 0300 0000 0000 0000 0000 0000 0000 0000  ................
0000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
0000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
0000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
0000060: 0000 0000                                ....



Dr. Peter A. J. Liggatt
President
MicroDecisions, Inc.
Tel:  407-843-1550
E-mail: pliggatt@microdecisions.com<mailto:pliggatt@microdecisions.com>
Website: www.microbase.com<http://www.microbase.com/>

**Comment by shawnlaffan** [comment]
An empty shapefile could be added to the t/testdata folder, and then used for testing.  Is this something you're able to do?  

(Also - it's a bit cleaner to respond to tickets using the github interface, as github does not hide the email trail).

**Comment by shawnlaffan** [comment]
...although an empty shapefile was added in 7d9ad1d2fadc44b23c6d2805f1efc609a4094ebc so it should only need the code part.

**Comment by shawnlaffan** [comment]
Updated code is on CPAN under release 2.66.
https://metacpan.org/release/SLAFFAN/Geo-ShapeFile-2.66

Marking as fixed.
