### ISSUE TITLE
Geo::ShapeFile::type_is argument type

### ISSUE THREAD

**Issue by poslfit** [shawnlaffan/Geo-ShapeFile#26]
The man page for `Geo::ShapeFile` says that method `type_is` takes argument `$numeric_type`, but it is actually expecting a case-insensitive human-readable string type instead.

**Comment by shawnlaffan** [comment]
Thanks for the report.  

Line is https://github.com/shawnlaffan/Geo-ShapeFile/blob/3544adcf6ddc7b65da1c3ce3a478ef7b499fd15d/lib/Geo/ShapeFile.pm#L916

Code is at https://github.com/shawnlaffan/Geo-ShapeFile/blob/3544adcf6ddc7b65da1c3ce3a478ef7b499fd15d/lib/Geo/ShapeFile.pm#L240

**Comment by shawnlaffan** [comment]
Version 3.01 has been released and uploaded to CPAN.  
https://metacpan.org/pod/release/SLAFFAN/Geo-ShapeFile-3.01/lib/Geo/ShapeFile.pm
