### ISSUE TITLE
test data - generate non-ascii file names with testing

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/Geo-ShapeFile#30]
The 3.02 release is seeing failures due to missing files.  This is likely because of file name mangling somewhere along the way.  

http://www.cpantesters.org/cpan/report/24b76368-b315-11ed-bb9e-81ad2b9d4dbf

The file with non-ascii characters is just a copy of one of the other files anyway, so we might as well generate it on the system as we go.

**Comment by michal-josef-spacek** [comment]
```make dist``` not working

**Comment by shawnlaffan** [comment]
Updated files are now on CPAN as v3.03: https://metacpan.org/release/SLAFFAN/Geo-ShapeFile-3.03

Will monitor cpan testers and close if all goes well.

**Comment by shawnlaffan** [comment]
Test are green so far where previously it was all red.  Closing issue. 
http://fast-matrix.cpantesters.org/?dist=Geo-ShapeFile+3.03
